// Generated by tools/make-template.py from the ticket artwork. Positions are in pixels
// of the 300-dpi ticket image; prices can be edited here directly.
window.TICKET_TEMPLATE = {
  "id": "barber-a6-v1",
  "name": "Barber ticket (A6)",
  "width": 1748,
  "height": 1240,
  "currency": "GBP",
  "boxes": [
    {
      "code": "clipper-1",
      "section": "Hair",
      "name": "Clipper 1 no",
      "price": 9.75,
      "rect": [
        845,
        329,
        53,
        21
      ]
    },
    {
      "code": "man-clipper-scissors",
      "section": "Hair",
      "name": "Man Clipper/Scissors",
      "price": 13.75,
      "rect": [
        845,
        366,
        53,
        21
      ]
    },
    {
      "code": "man-scissors-cut",
      "section": "Hair",
      "name": "Man Scissors Cut",
      "price": 15.75,
      "rect": [
        845,
        406,
        53,
        21
      ]
    },
    {
      "code": "skin-fade",
      "section": "Hair",
      "name": "Skin Fade",
      "price": 15.75,
      "rect": [
        845,
        448,
        53,
        21
      ]
    },
    {
      "code": "wash",
      "section": "Hair",
      "name": "Wash",
      "price": 2.0,
      "rect": [
        845,
        479,
        53,
        21
      ]
    },
    {
      "code": "man-booking",
      "section": "Hair",
      "name": "Man Booking",
      "price": 19.75,
      "rect": [
        846,
        523,
        53,
        21
      ]
    },
    {
      "code": "man-wash",
      "section": "Hair",
      "name": "Man Wash",
      "price": 9.75,
      "rect": [
        846,
        558,
        53,
        21
      ]
    },
    {
      "code": "beard-trim",
      "section": "Hair",
      "name": "Beard Trim",
      "price": 5.75,
      "rect": [
        846,
        600,
        53,
        21
      ]
    },
    {
      "code": "neck-trim",
      "section": "Hair",
      "name": "Neck Trim",
      "price": 4.75,
      "rect": [
        846,
        637,
        53,
        21
      ]
    },
    {
      "code": "line-up",
      "section": "Hair",
      "name": "Line Up",
      "price": 2.0,
      "rect": [
        846,
        679,
        53,
        21
      ]
    },
    {
      "code": "beard-wet-shave",
      "section": "Hair",
      "name": "Beard Wet Shave/Foil Shaver",
      "price": 9.75,
      "rect": [
        846,
        718,
        53,
        21
      ]
    },
    {
      "code": "head-wet-shave",
      "section": "Hair",
      "name": "Head Wet Shave/Foil Shaver",
      "price": 12.75,
      "rect": [
        846,
        759,
        53,
        21
      ]
    },
    {
      "code": "hot-towel",
      "section": "Hair",
      "name": "Hot Towel",
      "price": 2.0,
      "rect": [
        846,
        799,
        53,
        21
      ]
    },
    {
      "code": "toner",
      "section": "Colour",
      "name": "Toner",
      "price": 19.75,
      "rect": [
        460,
        873,
        53,
        21
      ]
    },
    {
      "code": "colour-bleach-short",
      "section": "Colour",
      "name": "Colour/Bleach Short",
      "price": 29.75,
      "rect": [
        846,
        913,
        53,
        21
      ]
    },
    {
      "code": "colour-bleach-medium",
      "section": "Colour",
      "name": "Colour/Bleach Medium",
      "price": 39.75,
      "rect": [
        846,
        951,
        53,
        21
      ]
    },
    {
      "code": "colour-bleach-long",
      "section": "Colour",
      "name": "Colour/Bleach Long",
      "price": 49.75,
      "rect": [
        846,
        993,
        53,
        21
      ]
    },
    {
      "code": "beard-colour",
      "section": "Colour",
      "name": "Beard Colour",
      "price": 9.75,
      "rect": [
        846,
        1033,
        53,
        21
      ]
    },
    {
      "code": "cap-highlights",
      "section": "Colour",
      "name": "Cap Highlights",
      "price": 37.75,
      "rect": [
        846,
        1071,
        53,
        21
      ]
    },
    {
      "code": "senior",
      "section": "Discounts",
      "name": "Senior (60+)",
      "price": null,
      "rect": [
        716,
        1130,
        53,
        21
      ]
    },
    {
      "code": "nhs-student",
      "section": "Discounts",
      "name": "NHS/Student",
      "price": null,
      "rect": [
        716,
        1192,
        53,
        21
      ]
    },
    {
      "code": "eyebrow-wax",
      "section": "Grooming",
      "name": "Eyebrow Wax",
      "price": 9.75,
      "rect": [
        1680,
        374,
        53,
        21
      ]
    },
    {
      "code": "eyebrow-threading",
      "section": "Grooming",
      "name": "Eyebrow Threading",
      "price": 12.75,
      "rect": [
        1680,
        412,
        53,
        21
      ]
    },
    {
      "code": "nose-wax",
      "section": "Grooming",
      "name": "Nose Wax",
      "price": 4.75,
      "rect": [
        1680,
        452,
        53,
        21
      ]
    },
    {
      "code": "ear-wax",
      "section": "Grooming",
      "name": "Ear Wax",
      "price": 4.75,
      "rect": [
        1680,
        490,
        53,
        21
      ]
    },
    {
      "code": "eyebrow-tint",
      "section": "Grooming",
      "name": "Eyebrow Tint",
      "price": 7.75,
      "rect": [
        1680,
        532,
        53,
        21
      ]
    },
    {
      "code": "mustache-tint",
      "section": "Grooming",
      "name": "Mustache Tint",
      "price": 9.75,
      "rect": [
        1680,
        572,
        53,
        21
      ]
    },
    {
      "code": "sides-threading",
      "section": "Grooming",
      "name": "Sides Threading",
      "price": 9.75,
      "rect": [
        1680,
        616,
        53,
        21
      ]
    },
    {
      "code": "full-face-brows-threading",
      "section": "Grooming",
      "name": "Full Face & Brows Threading",
      "price": 32.75,
      "rect": [
        1680,
        656,
        53,
        21
      ]
    },
    {
      "code": "forehead-threading",
      "section": "Grooming",
      "name": "Forehead Threading",
      "price": 9.75,
      "rect": [
        1680,
        695,
        53,
        21
      ]
    },
    {
      "code": "cheeks-wax",
      "section": "Grooming",
      "name": "Cheeks Wax",
      "price": 4.75,
      "rect": [
        1680,
        732,
        53,
        21
      ]
    },
    {
      "code": "perm-top-head",
      "section": "Perm",
      "name": "Perm Top Head",
      "price": 50.0,
      "rect": [
        1681,
        818,
        53,
        21
      ]
    },
    {
      "code": "perm-top-sides",
      "section": "Perm",
      "name": "Perm Top & Sides",
      "price": 70.0,
      "rect": [
        1681,
        858,
        53,
        21
      ]
    },
    {
      "code": "crazy-colours",
      "section": "Colour",
      "name": "Crazy Colours",
      "price": 24.75,
      "rect": [
        1042,
        872,
        53,
        21
      ]
    },
    {
      "code": "perm-medium-hair",
      "section": "Perm",
      "name": "Perm Medium Hair",
      "price": 90.0,
      "rect": [
        1681,
        898,
        53,
        21
      ]
    },
    {
      "code": "perm-long-hair",
      "section": "Perm",
      "name": "Perm Long Hair",
      "price": 120.0,
      "rect": [
        1681,
        936,
        53,
        21
      ]
    },
    {
      "code": "brazilian-top-head",
      "section": "Brazilian/Botox",
      "name": "Brazilian/Botox Top Head",
      "price": 50.0,
      "rect": [
        1680,
        1044,
        53,
        21
      ]
    },
    {
      "code": "brazilian-top-sides",
      "section": "Brazilian/Botox",
      "name": "Brazilian/Botox Top & Sides",
      "price": 70.0,
      "rect": [
        1680,
        1083,
        53,
        21
      ]
    },
    {
      "code": "brazilian-medium-hair",
      "section": "Brazilian/Botox",
      "name": "Brazilian/Botox Medium Hair",
      "price": 98.0,
      "rect": [
        1680,
        1123,
        53,
        21
      ]
    },
    {
      "code": "six-free-cut",
      "section": "Discounts",
      "name": "6th Free Cut",
      "price": null,
      "rect": [
        1012,
        1160,
        53,
        21
      ]
    },
    {
      "code": "brazilian-long-hair",
      "section": "Brazilian/Botox",
      "name": "Brazilian/Botox Long Hair",
      "price": 120.0,
      "rect": [
        1680,
        1165,
        53,
        21
      ]
    }
  ],
  "fields": [
    {
      "key": "staff",
      "label": "Stylist (C number)",
      "rect": [
        618,
        185,
        512,
        81
      ]
    },
    {
      "key": "treatments",
      "label": "How many treatments",
      "rect": [
        25,
        1116,
        232,
        120
      ]
    },
    {
      "key": "tips",
      "label": "Tips",
      "rect": [
        265,
        1116,
        232,
        120
      ]
    }
  ]
};
